### ISSUE TITLE
Problem Adding Student

### ISSUE THREAD

**Issue by freelancewebdev** [nomadicjosh/eduTrac-SIS#42]
Sorry Joshua, another one.

I added a person, gave them a person type of 'student' and a role of 'student'.  Saved them.

Located them using person search and then created an application for an academic program I have set up.  I have also set up my course and a corresponding course section

I do my applicant search, choose the 'Create Student' action, complete the form and submit and am greeted with a '409 Conflict Error'

In the error log I see:
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'acadLevelCode' in 'field list' [] []
The student record is added correctly in the database but not in the sacp table which I guess is the one that links the student to their programme, advisor etc.

I guess this is because there's no column for acadLevelCode in the sacp table - is it OK to add one?

**Comment by nomadicjosh** [comment]
No, it needs to be taken out because it can be found in the virtual table (v_sacp). Open _app/routers/student.router.php_. Search for and delete the following line: `$sacp->acadLevelCode = _trim($app->req->post['acadLevelCode']);`

You will also need to create a student academic level (stal) record because that might not have populated as well.

**Comment by freelancewebdev** [comment]
Yup, will definitely need to sort that out because I had removed the student record from the students table.  Thanks for the heads up.
